- client/src/Components/Calendar.js
- client/src/Components/CreateEvent.js
- client/src/Components/EditEvent.js
- client/src/Components/EditProfile.js
- client/src/Components/EventComponent.js
- client/src/Components/Footer.js
- client/src/Components/Hero.js
- client/src/Components/LogNavBar.js
- client/src/Components/Login.js
- client/src/Components/OrgComponent.js
- client/src/Components/OrgSignUp.js
- client/src/Components/PreNavBar.js
- client/src/Components/SearchResList.js
- client/src/Components/Searchbar.js
- client/src/Components/SideList.js
- client/src/Components/UserSignUp.js
Added pages to Components 
Added templates and sudo 
5
> Basic components built, light touch of sudo

- client/package-lock.json
- client/package.json
- client/src/App.js
- client/src/Components/EventComponent.js
- client/src/Components/LogNavBar.js
- client/src/Components/Logo.js
- client/src/Components/OrgComponent.js
- client/src/Components/Searchbar.js
- client/src/Components/SideList.js
- client/src/pages/Home.js
- client/src/scss/App.scss
Added in react big calendar
Added in moment
Worked on adding all components needed to make up page
I think we need to discuss where the nav and footer live because they shouldn't be rerendered every time the page is made.
> User home page

- server/models/event.js
- server/models/user.js
Models
Removed organization reference from event model and changed into a string. Also added event reference to user.
4
> Model changes to remove organization reference

- server/package-lock.json
- server/package.json
- server/routes/organizations.js
- server/seedDB.js
naming conventions
some naming conventions were different between models and controllers. changed those to match
4
> made sure naming conventions were the same

- client/src/App.js
- client/src/Components/Content.js
- client/src/Components/Footer.js
- client/src/Components/LogNavBar.js
- client/src/Components/Login.js
- client/src/Components/Logo.js
- client/src/Components/PreNavBar.js
- client/src/pages/Landing.js
We didn't want navigation rerendering constantly
- Moved Navigation component out of all pages it was in and into the app js directly
- Created a content component to hold all the routes for rendering components
4
- Routes are still not quite right.
> Refactor component tree

- client/src/Components/Content.js
- client/src/Components/Logo.js
Wasn't previously rendering the pages selected from navigation bar
Figured out wasn't adding the exact flag in the correct place.
5
> Solved Navigation Issue

- client/src/App.js
- client/src/Components/Content.js
- client/src/Components/LogNavBar.js
- client/src/Components/UserSignUp.js
- client/src/pages/Home.js
- client/src/scss/App.scss
Adding Navigation to the other pages in the nav bars so we can see them as we work on them
- Added back in basic "/" route that somehow got deleted
- Routes and Links added for post auth
- Fixed an issue with the calendar on home page
- Fixed export issue with user sign up
5
> Post auth nav

- server/models/organization.js
- server/routes/users.js
- server/seedDB.js
User GET routes. Organization model terminology clarification
GET routes work now, and changed "name" to "orgname" for future clarity on names
4
> User GET routes fixed, changed terminology for clarity in Organization model

- server/models/event.js
- server/models/user.js
- server/routes/events.js
- server/routes/organizations.js
- server/routes/users.js
- server/seedDB.js
- server/server.js
Modified the index, user, organization, and server.js files
4
> I did a little modification on the user route

- client/src/Components/Searchbar.js
- client/src/hooks/SearchHook.js
- client/src/pages/SearchResultsUser.js
Issue #14 
- Added some cool search navigation that'll create a url with a query field
- Got a cool sick custom hook
5
- I've been rewatch A Very Potter Musical in the background, so that's the Hufflepuff reference.
> User search results

- client/src/Components/SearchResList.js
- client/src/pages/SearchResultsUser.js
Issue #28 
- Added result list to page component
- Able to grab the query from the params of the url
5
> Search page completed

- client/src/Components/Content.js
- client/src/pages/ProfileUser.js
#29 
- Added some basic layout for a user profile based on saved info from the user model
5 
- Also linked it to Edit Profile page.
> User profile

- client/src/Components/Content.js
- client/src/pages/OrganizationUser.js
#32 
- Added a basic layout for organization info
5
> Added organization page layout

- client/src/Components/EditProfile.js
- client/src/pages/OrganizationUser.js
Needed to fix some bugs
- Used a foreach where a map was expected
- Needed to pass props to a component
5
> Some some bugs

- client/src/Components/Content.js
- client/src/Components/EditProfile.js
- client/src/pages/Home.js
Issue #68 
- Added the logic for when a valid user is passed to the home page following a successful login.
4
I won't really know if it works until we're signing people in, but I'm pretty sure this is how you set up for it.
> Get user home

- client/src/Components/Content.js
- client/src/Components/EditProfile.js
- client/src/pages/EditProfileUser.js
- client/src/pages/ProfileUser.js
#66 
- Added user calls to Profile page
- Added user calls to Edit Profile component
- Added validations on if user is null or not
- Added type validations to text fields in edit profile
4
Set up the same as Home, so if that works, this'll work
> Added user infomration calls to profile

- client/src/Components/UserSignUp.js
- client/src/pages/SignupUser.js
getting user profiles created
angry semi colon at the bottom
2.5
> angry semi colon on Signup

- client/src/Components/ErrorMessage.js
- client/src/pages/Home.js
Issue #70 
- Added fetch 
- Added useState for the state of events and an error
- Added an error component to show up if we can't get events.
5 
- Left the fetch url empty for now until we've ironed out the BE
> Added base for getting events, still need endpoint and base url

- client/src/pages/Home.js
#69 (nice)
- Added fetch call base for organizations on the home page as well
5
- Just as with PR #83 , this will have to be updated later to add the actual endpoints
> Get user organizations home

- client/src/Components/Content.js
- client/src/Components/OrgComponent.js
- client/src/Components/UserSignUp.js
- client/src/pages/Home.js
- client/src/pages/OrganizationUser.js
- #73
- #74 
- Set up fetch for specific organziation
- Added Link to specific organization to organization component
- Set up fetch for events of an organization if organization is successfully gotten
- Changed error from a string to an object of messages.
- Small bug fixes
4
These are gonna be a 4 until I actually test against the database.
> Get organization

- README.md
#51 
- Added a new section giving credit to Yashoma, Kennan, and Nick's project that helped us out
5
Giving credit where credit is due is nice :heart:
> Added credit to meet out

- client/src/pages/SearchResultsUser.js
attempting to render search results, doubt its gonna work
1
> search stuff, probably wrong

- .env
- .gitignore
- server/models/event.js
- server/models/index.js
- server/models/organization.js
- server/models/user.js
- server/routes/auth.js
- server/routes/events.js
- server/routes/organizations.js
- server/routes/users.js
- server/server.js
M:M relationship, model changes, and auth.js (back-end)
- [64](https://github.com/melissay94/GA-Team-4/issues/64)
- [86](https://github.com/melissay94/GA-Team-4/issues/86)
- [87](https://github.com/melissay94/GA-Team-4/issues/87)
- model changes to include M:M relationship
- M:M relationship between event and user has been created and tested. 👍🏽
- auth.js implementation
4
- Let me know if any changes are needed. M:M should be working from my tests. 
- bcrypt tested and works as shown in results of M:M testing
- Auth.js (back-end) needs testing once front-end auth is done.
> M:M relationship, model changes, and auth.js (back-end)

- client/src/pages/SearchResultsUser.js
Hotfix for bugs I missed in PR review
> Search bug fixes

- client/src/Components/OrgComponent.js
- client/src/Components/SideList.js
- client/src/pages/Home.js
- server/models/event.js
- server/models/organization.js
- server/models/user.js
- server/routes/auth.js
- server/routes/users.js
- server/seedDB.js
#89 #87
- Added events call to home page
- Added organizations call to home page
- Did some renaming in the models to fix errors
- Added default organization to new users
- Added and changed some user routes to get relevant information
5
It looks great, sorry I touched so much.
> Show events home

- client/src/Components/EventComponent.js
- client/src/Components/OrgComponent.js
- client/src/Components/SearchResList.js
- client/src/pages/ProfileUser.js
- client/src/pages/SearchResultsUser.js
- server/routes/events.js
- server/routes/organizations.js
#76 
- Small server changes to get organization name for events
- small server change to get organizations from their home url
- Added all information into the little blurb that shows up!
- You can search "event", "events", "organization", or "organizations".
5
Search!
> You can see events and organizations in search

- client/src/App.js
- client/src/Components/Footer.js
- client/src/Components/Hero.js
- client/src/pages/Landing.js
- client/src/scss/App.scss
#104 
- Redid css for page structure to be able to have footer stick to bottom of view
- Changed footer to inline elements
- Gave it a nice light gray background
4
> Design footer

- client/src/Components/Calendar.js
- client/src/Components/EventHomeItem.js
- client/src/Components/EventList.js
- client/src/Components/OrgHomeItem.js
- client/src/Components/OrgList.js
- client/src/pages/Home.js
#106 
- There's spacing for stuff
- Added cool material ui components like cards
- Some nice colors!
- Events on the calendar y'all
4
Can't fit the whole thing, but this is most of it.
> Design home

- client/src/Components/OrgSearchItem.js
- client/src/pages/OrganizationUser.js
- server/routes/organizations.js
- server/routes/users.js
#75 #77 
- Added organization name, events, and volunteer count
5
> Added organization specific data to show up and add to user

- client/src/Components/EventSearchItem.js
- client/src/Components/OrgSearchItem.js
- client/src/pages/SearchResultsUser.js
#107 
- Centered Results
- Lined up header to match with results
4
> Design search

- client/src/pages/OrganizationUser.js
User Organization UI
Not working
1
> Organization Material UI
